// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJFBgkUswW-8Ua73Zn54KlbsPe5FzkLRQ',
    appId: '1:271012911373:web:4b4782a301e68e555db844',
    messagingSenderId: '271012911373',
    projectId: 'ecommerce-92e89',
    authDomain: 'ecommerce-92e89.firebaseapp.com',
    storageBucket: 'ecommerce-92e89.firebasestorage.app',
    measurementId: 'G-45MEX3KM33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcJiJOtfzN66kcOvtnJUHKjBaEhSp1ifQ',
    appId: '1:271012911373:android:4693ef34f9d62b795db844',
    messagingSenderId: '271012911373',
    projectId: 'ecommerce-92e89',
    storageBucket: 'ecommerce-92e89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSWwJWsQWLeTIJQUc7rhomZpqdAfhPuvA',
    appId: '1:271012911373:ios:70dacd2adb612f3f5db844',
    messagingSenderId: '271012911373',
    projectId: 'ecommerce-92e89',
    storageBucket: 'ecommerce-92e89.firebasestorage.app',
    iosBundleId: 'com.example.ecommercesystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSWwJWsQWLeTIJQUc7rhomZpqdAfhPuvA',
    appId: '1:271012911373:ios:70dacd2adb612f3f5db844',
    messagingSenderId: '271012911373',
    projectId: 'ecommerce-92e89',
    storageBucket: 'ecommerce-92e89.firebasestorage.app',
    iosBundleId: 'com.example.ecommercesystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJFBgkUswW-8Ua73Zn54KlbsPe5FzkLRQ',
    appId: '1:271012911373:web:dc22bb07e0e40eb65db844',
    messagingSenderId: '271012911373',
    projectId: 'ecommerce-92e89',
    authDomain: 'ecommerce-92e89.firebaseapp.com',
    storageBucket: 'ecommerce-92e89.firebasestorage.app',
    measurementId: 'G-D4XLWRX95V',
  );
}
